language: python
python:
        - "3.5.2"
services:
    - postgresql
before_script:
        - psql -c 'create database catalog_testdb;' -U postgres
        - psql -c "create user jp with password 'cavier';" -U postgres
        - flask db upgrade
install:
        - pip install -r requirements.txt
script:
        - pytest
after_success:
        - coverage run -m pytest
        - coverage report
