language: python
python:
        - "3.5.2"
env:
  global:
    - TEST_DATABASE_URL="postgresql+psycopg2://jp:cavier@localhost:5432/catalog_testdb"
services:
    - postgresql
before_script:
        - psql -c 'create database catalog_testdb;' -U postgres
        - psql -c "create user jp with password 'cavier';" -U postgres
        
install:
        - pip install -r requirements.txt
script:
        - flask db upgrade
        - pytest
after_success:
        - coverage run -m pytest
        - coverage report
