language: python
python:
        - "3.5.2"
env:
  global:
    - TEST_DATABASE_URL="postgresql+psycopg2://jp:cavier@localhost:5432/catalog_testdb"
    - CODECOV_TOKEN="cc94657c-fd77-4294-ad33-5056ec5e45ae"
services:
    - postgresql
before_script:
        - psql -c 'create database catalog_testdb;' -U postgres
        - psql -c "create user jp with password 'cavier';" -U postgres
install:
        - pip install -r requirements.txt
script:
        - pytest
after_success:
        - coverage run -m pytest
after_success:
        - coverage report
